// ============================================================
// UDISE+ CONFIGURATION
// All UDISE categories, fields, validation rules
// Based on UDISE+ 2024-25 Official Data Capture Format
// ============================================================

// ─── UDISE CATEGORIES ───────────────────────────────────────

export interface UdiseField {
    key: string;
    label: string;
    type: "text" | "date" | "select" | "number" | "tel" | "email" | "checkbox" | "textarea";
    required: boolean;           // UDISE mandatory?
    source: "direct" | "extras"; // stored in student column or extras JSON
    placeholder?: string;
    options?: Array<{ value: string; label: string }>;
    validation?: {
      pattern?: string;
      min?: number;
      max?: number;
      minLength?: number;
      maxLength?: number;
      message?: string;
    };
  }
  
  export interface UdiseCategory {
    id: string;
    name: string;
    icon: string;
    description: string;
    fields: UdiseField[];
  }
  
  // ─── CATEGORY A: BASIC INFORMATION ──────────────────────────
  
  const basicFields: UdiseField[] = [
    {
      key: "first_name",
      label: "First Name",
      type: "text",
      required: true,
      source: "direct",
      placeholder: "As per birth certificate",
      validation: { minLength: 1, maxLength: 100, message: "First name is required" },
    },
    {
      key: "last_name",
      label: "Last Name",
      type: "text",
      required: true,
      source: "direct",
      placeholder: "Family name / Surname",
      validation: { minLength: 1, maxLength: 100, message: "Last name is required" },
    },
    {
      key: "date_of_birth",
      label: "Date of Birth",
      type: "date",
      required: true,
      source: "direct",
      validation: { message: "Valid date of birth is required" },
    },
    {
      key: "gender",
      label: "Gender",
      type: "select",
      required: true,
      source: "direct",
      options: [
        { value: "male", label: "Male" },
        { value: "female", label: "Female" },
        { value: "other", label: "Transgender" },
      ],
    },
    {
      key: "aadhaar_number",
      label: "Aadhaar Number",
      type: "text",
      required: false,
      source: "direct",
      placeholder: "12-digit Aadhaar number",
      validation: { pattern: "^\\d{12}$", message: "Aadhaar must be 12 digits" },
    },
    {
      key: "apaar_id",
      label: "APAAR ID",
      type: "text",
      required: false,
      source: "direct",
      placeholder: "Auto-generated by UDISE",
    },
    {
      key: "blood_group",
      label: "Blood Group",
      type: "select",
      required: false,
      source: "direct",
      options: [
        { value: "unknown", label: "Not Known" },
        { value: "A+", label: "A+" },
        { value: "A-", label: "A-" },
        { value: "B+", label: "B+" },
        { value: "B-", label: "B-" },
        { value: "AB+", label: "AB+" },
        { value: "AB-", label: "AB-" },
        { value: "O+", label: "O+" },
        { value: "O-", label: "O-" },
      ],
    },
  ];
  
  // ─── CATEGORY B: FAMILY DETAILS ─────────────────────────────
  
  const familyFields: UdiseField[] = [
    {
      key: "father_name",
      label: "Father's Name",
      type: "text",
      required: true,
      source: "extras",
      placeholder: "Full name",
    },
    {
      key: "father_occupation",
      label: "Father's Occupation",
      type: "text",
      required: false,
      source: "extras",
      placeholder: "e.g. Business, Service, Farming",
    },
    {
      key: "father_qualification",
      label: "Father's Education",
      type: "select",
      required: false,
      source: "extras",
      options: [
        { value: "illiterate", label: "Illiterate" },
        { value: "below_10th", label: "Below 10th" },
        { value: "10th_pass", label: "10th Pass" },
        { value: "12th_pass", label: "12th Pass" },
        { value: "graduate", label: "Graduate" },
        { value: "post_graduate", label: "Post Graduate" },
        { value: "doctorate", label: "Doctorate" },
        { value: "professional", label: "Professional Degree" },
      ],
    },
    {
      key: "father_mobile",
      label: "Father's Mobile",
      type: "tel",
      required: true,
      source: "extras",
      placeholder: "10-digit number",
      validation: { pattern: "^[6-9]\\d{9}$", message: "Valid 10-digit mobile number required" },
    },
    {
      key: "mother_name",
      label: "Mother's Name",
      type: "text",
      required: true,
      source: "extras",
      placeholder: "Full name",
    },
    {
      key: "mother_occupation",
      label: "Mother's Occupation",
      type: "text",
      required: false,
      source: "extras",
      placeholder: "e.g. Housewife, Service, Business",
    },
    {
      key: "mother_qualification",
      label: "Mother's Education",
      type: "select",
      required: false,
      source: "extras",
      options: [
        { value: "illiterate", label: "Illiterate" },
        { value: "below_10th", label: "Below 10th" },
        { value: "10th_pass", label: "10th Pass" },
        { value: "12th_pass", label: "12th Pass" },
        { value: "graduate", label: "Graduate" },
        { value: "post_graduate", label: "Post Graduate" },
        { value: "doctorate", label: "Doctorate" },
        { value: "professional", label: "Professional Degree" },
      ],
    },
    {
      key: "mother_mobile",
      label: "Mother's Mobile",
      type: "tel",
      required: false,
      source: "extras",
      placeholder: "10-digit number",
      validation: { pattern: "^[6-9]\\d{9}$", message: "Valid 10-digit mobile number" },
    },
    {
      key: "guardian_name",
      label: "Guardian Name (if applicable)",
      type: "text",
      required: false,
      source: "extras",
    },
    {
      key: "guardian_relation",
      label: "Guardian Relation",
      type: "select",
      required: false,
      source: "extras",
      options: [
        { value: "", label: "Not Applicable" },
        { value: "uncle", label: "Uncle" },
        { value: "aunt", label: "Aunt" },
        { value: "grandfather", label: "Grandfather" },
        { value: "grandmother", label: "Grandmother" },
        { value: "brother", label: "Elder Brother" },
        { value: "sister", label: "Elder Sister" },
        { value: "other", label: "Other" },
      ],
    },
    {
      key: "family_income",
      label: "Annual Family Income",
      type: "select",
      required: false,
      source: "extras",
      options: [
        { value: "", label: "Not Specified" },
        { value: "below_1L", label: "Below ₹1 Lakh" },
        { value: "1L_3L", label: "₹1 - 3 Lakh" },
        { value: "3L_5L", label: "₹3 - 5 Lakh" },
        { value: "5L_10L", label: "₹5 - 10 Lakh" },
        { value: "10L_25L", label: "₹10 - 25 Lakh" },
        { value: "above_25L", label: "Above ₹25 Lakh" },
      ],
    },
    {
      key: "email",
      label: "Family Email",
      type: "email",
      required: false,
      source: "direct",
      placeholder: "parent@email.com",
    },
  ];
  
  // ─── CATEGORY C: SOCIAL CATEGORY ────────────────────────────
  
  const categoryFields: UdiseField[] = [
    {
      key: "category",
      label: "Social Category",
      type: "select",
      required: true,
      source: "direct",
      options: [
        { value: "general", label: "General" },
        { value: "obc", label: "OBC (Other Backward Class)" },
        { value: "sc", label: "SC (Scheduled Caste)" },
        { value: "st", label: "ST (Scheduled Tribe)" },
        { value: "ews", label: "EWS (Economically Weaker Section)" },
        { value: "not_specified", label: "Not Specified" },
      ],
    },
    {
      key: "religion",
      label: "Religion",
      type: "select",
      required: false,
      source: "direct",
      options: [
        { value: "hindu", label: "Hindu" },
        { value: "muslim", label: "Muslim" },
        { value: "christian", label: "Christian" },
        { value: "sikh", label: "Sikh" },
        { value: "buddhist", label: "Buddhist" },
        { value: "jain", label: "Jain" },
        { value: "parsi", label: "Parsi" },
        { value: "other", label: "Other" },
        { value: "not_specified", label: "Not Specified" },
      ],
    },
    {
      key: "mother_tongue",
      label: "Mother Tongue",
      type: "text",
      required: false,
      source: "extras",
      placeholder: "e.g. Hindi, Tamil, Bengali",
    },
    {
      key: "is_bpl",
      label: "BPL (Below Poverty Line)",
      type: "checkbox",
      required: false,
      source: "extras",
    },
    {
      key: "bpl_number",
      label: "BPL Card Number",
      type: "text",
      required: false,
      source: "extras",
      placeholder: "If BPL, enter card number",
    },
    {
      key: "is_rte",
      label: "RTE (Right to Education) Beneficiary",
      type: "checkbox",
      required: false,
      source: "extras",
    },
    {
      key: "is_minority",
      label: "Belongs to Minority Community",
      type: "checkbox",
      required: false,
      source: "extras",
    },
    {
      key: "is_cwsn",
      label: "CWSN (Child with Special Needs)",
      type: "checkbox",
      required: false,
      source: "extras",
    },
    {
      key: "disability_type",
      label: "Type of Disability (if CWSN)",
      type: "select",
      required: false,
      source: "extras",
      options: [
        { value: "", label: "Not Applicable" },
        { value: "visual", label: "Visual Impairment" },
        { value: "hearing", label: "Hearing Impairment" },
        { value: "speech", label: "Speech Impairment" },
        { value: "locomotor", label: "Locomotor Disability" },
        { value: "intellectual", label: "Intellectual Disability" },
        { value: "autism", label: "Autism" },
        { value: "cerebral_palsy", label: "Cerebral Palsy" },
        { value: "learning", label: "Learning Disability" },
        { value: "multiple", label: "Multiple Disabilities" },
        { value: "other", label: "Other" },
      ],
    },
  ];
  
  // ─── CATEGORY D: ADDRESS ────────────────────────────────────
  
  const addressFields: UdiseField[] = [
    {
      key: "address_line1",
      label: "House No. / Street / Locality",
      type: "text",
      required: true,
      source: "direct",
      placeholder: "Full address line 1",
    },
    {
      key: "address_line2",
      label: "Area / Landmark",
      type: "text",
      required: false,
      source: "direct",
      placeholder: "Near / Opposite / Behind",
    },
    {
      key: "city",
      label: "Village / Town / City",
      type: "text",
      required: true,
      source: "direct",
    },
    {
      key: "district",
      label: "District",
      type: "text",
      required: false,
      source: "extras",
    },
    {
      key: "state",
      label: "State",
      type: "text",
      required: true,
      source: "direct",
    },
    {
      key: "pincode",
      label: "Pincode",
      type: "text",
      required: true,
      source: "direct",
      placeholder: "6-digit pincode",
      validation: { pattern: "^\\d{6}$", message: "Pincode must be 6 digits" },
    },
    {
      key: "distance_from_school",
      label: "Distance from School (km)",
      type: "number",
      required: false,
      source: "extras",
      placeholder: "In kilometers",
      validation: { min: 0, max: 100 },
    },
    {
      key: "transport_mode",
      label: "Mode of Transport to School",
      type: "select",
      required: false,
      source: "extras",
      options: [
        { value: "", label: "Not Specified" },
        { value: "walking", label: "Walking" },
        { value: "bicycle", label: "Bicycle" },
        { value: "school_bus", label: "School Bus" },
        { value: "public_transport", label: "Public Transport" },
        { value: "auto_rickshaw", label: "Auto Rickshaw" },
        { value: "private_vehicle", label: "Private Vehicle" },
        { value: "other", label: "Other" },
      ],
    },
  ];
  
  // ─── CATEGORY E: ACADEMIC ───────────────────────────────────
  
  const academicFields: UdiseField[] = [
    {
      key: "roll_number",
      label: "Roll Number",
      type: "text",
      required: false,
      source: "direct",
    },
    {
      key: "medium_of_instruction",
      label: "Medium of Instruction",
      type: "select",
      required: false,
      source: "extras",
      options: [
        { value: "english", label: "English" },
        { value: "hindi", label: "Hindi" },
        { value: "tamil", label: "Tamil" },
        { value: "telugu", label: "Telugu" },
        { value: "kannada", label: "Kannada" },
        { value: "malayalam", label: "Malayalam" },
        { value: "bengali", label: "Bengali" },
        { value: "marathi", label: "Marathi" },
        { value: "gujarati", label: "Gujarati" },
        { value: "punjabi", label: "Punjabi" },
        { value: "odia", label: "Odia" },
        { value: "urdu", label: "Urdu" },
        { value: "other", label: "Other" },
      ],
    },
    {
      key: "board",
      label: "Board",
      type: "select",
      required: false,
      source: "extras",
      options: [
        { value: "cbse", label: "CBSE" },
        { value: "icse", label: "ICSE" },
        { value: "state", label: "State Board" },
        { value: "ib", label: "IB" },
        { value: "igcse", label: "IGCSE" },
        { value: "other", label: "Other" },
      ],
    },
    {
      key: "previous_school_name",
      label: "Previous School Name",
      type: "text",
      required: false,
      source: "direct",
      placeholder: "If transfer student",
    },
    {
      key: "previous_class",
      label: "Previous Class",
      type: "text",
      required: false,
      source: "direct",
    },
    {
      key: "tc_number",
      label: "Transfer Certificate Number",
      type: "text",
      required: false,
      source: "direct",
      placeholder: "TC number from previous school",
    },
  ];
  
  // ─── CATEGORY F: DOCUMENTS ──────────────────────────────────
  
  export const REQUIRED_DOCUMENTS = [
    { type: "photo", label: "Student Photo", required: true },
    { type: "birth_certificate", label: "Birth Certificate", required: true },
    { type: "aadhaar_card", label: "Aadhaar Card", required: false },
    { type: "caste_certificate", label: "Caste/Category Certificate", required: false },
    { type: "transfer_certificate", label: "Transfer Certificate", required: false },
    { type: "previous_marksheet", label: "Previous Marksheet", required: false },
    { type: "address_proof", label: "Address Proof", required: false },
    { type: "income_certificate", label: "Income Certificate", required: false },
    { type: "medical_certificate", label: "Medical Certificate", required: false },
  ];
  
  // ─── ALL CATEGORIES ─────────────────────────────────────────
  
  export const UDISE_CATEGORIES: UdiseCategory[] = [
    {
      id: "basic",
      name: "Basic Information",
      icon: "👤",
      description: "Student personal details",
      fields: basicFields,
    },
    {
      id: "family",
      name: "Family Details",
      icon: "👨‍👩‍👦",
      description: "Parents and guardian information",
      fields: familyFields,
    },
    {
      id: "category",
      name: "Social Category",
      icon: "🏷️",
      description: "Category, religion, special status",
      fields: categoryFields,
    },
    {
      id: "address",
      name: "Address & Transport",
      icon: "🏠",
      description: "Residential address and transport",
      fields: addressFields,
    },
    {
      id: "academic",
      name: "Academic Details",
      icon: "🎓",
      description: "Enrollment and academic information",
      fields: academicFields,
    },
    {
      id: "documents",
      name: "Documents",
      icon: "📄",
      description: "Required certificates and documents",
      fields: [], // handled separately
    },
  ];
  
  // ─── UDISE COMPLIANCE CALCULATOR ────────────────────────────
  
  export interface ComplianceResult {
    totalFields: number;
    filledFields: number;
    percentage: number;
    status: "complete" | "good" | "partial" | "pending";
    categoryResults: Array<{
      categoryId: string;
      categoryName: string;
      icon: string;
      totalFields: number;
      filledFields: number;
      percentage: number;
      missingFields: string[];
    }>;
    validationErrors: Array<{
      field: string;
      label: string;
      error: string;
    }>;
  }
  
  function isValueFilled(value: unknown): boolean {
    if (value === null || value === undefined) return false;
    if (typeof value === "string") {
      const v = value.trim();
      return v !== "" && v !== "unknown" && v !== "not_specified";
    }
    if (typeof value === "boolean") return true;
    if (typeof value === "number") return true;
    return false;
  }
  
  function getFieldValue(student: Record<string, unknown>, field: UdiseField): unknown {
    if (field.source === "direct") {
      return student[field.key];
    }
    // extras field
    const extras = (student.extras || {}) as Record<string, unknown>;
    return extras[field.key];
  }
  
  function validateField(value: unknown, field: UdiseField): string | null {
    if (!field.validation) return null;
    if (!value || !isValueFilled(value)) return null; // skip empty optional
  
    const strVal = String(value);
    const v = field.validation;
  
    if (v.pattern && !new RegExp(v.pattern).test(strVal)) {
      return v.message || `Invalid format for ${field.label}`;
    }
    if (v.minLength && strVal.length < v.minLength) {
      return `${field.label} must be at least ${v.minLength} characters`;
    }
    if (v.maxLength && strVal.length > v.maxLength) {
      return `${field.label} must be less than ${v.maxLength} characters`;
    }
    if (v.min !== undefined && Number(value) < v.min) {
      return `${field.label} must be at least ${v.min}`;
    }
    if (v.max !== undefined && Number(value) > v.max) {
      return `${field.label} must be less than ${v.max}`;
    }
    return null;
  }
  
  export function calculateUdiseCompliance(
    student: Record<string, unknown>
  ): ComplianceResult {
    let totalFields = 0;
    let filledFields = 0;
    const validationErrors: ComplianceResult["validationErrors"] = [];
  
    const categoryResults = UDISE_CATEGORIES.filter(
      (cat) => cat.id !== "documents"
    ).map((cat) => {
      const missingFields: string[] = [];
      let catTotal = 0;
      let catFilled = 0;
  
      cat.fields.forEach((field) => {
        // Only count required + important optional fields
        if (field.required) {
          catTotal++;
          totalFields++;
          const value = getFieldValue(student, field);
          if (isValueFilled(value)) {
            catFilled++;
            filledFields++;
          } else {
            missingFields.push(field.label);
          }
        } else {
          // Optional fields also count but with less weight
          const value = getFieldValue(student, field);
          if (isValueFilled(value)) {
            catTotal++;
            catFilled++;
            totalFields++;
            filledFields++;
          }
        }
  
        // Validate filled fields
        const value = getFieldValue(student, field);
        if (isValueFilled(value)) {
          const error = validateField(value, field);
          if (error) {
            validationErrors.push({
              field: field.key,
              label: field.label,
              error,
            });
          }
        }
      });
  
      // Ensure minimum totals
      if (catTotal === 0) catTotal = 1;
  
      return {
        categoryId: cat.id,
        categoryName: cat.name,
        icon: cat.icon,
        totalFields: catTotal,
        filledFields: catFilled,
        percentage: Math.round((catFilled / catTotal) * 100),
        missingFields,
      };
    });
  
    if (totalFields === 0) totalFields = 1;
    const percentage = Math.round((filledFields / totalFields) * 100);
  
    let status: ComplianceResult["status"];
    if (percentage >= 90) status = "complete";
    else if (percentage >= 70) status = "good";
    else if (percentage >= 40) status = "partial";
    else status = "pending";
  
    return {
      totalFields,
      filledFields,
      percentage,
      status,
      categoryResults,
      validationErrors,
    };
  }
  
  // ─── COMPLIANCE STATUS COLORS ───────────────────────────────
  
  export function getComplianceColors(status: ComplianceResult["status"]) {
    const map = {
      complete: {
        bg: "bg-green-500/10",
        text: "text-green-400",
        border: "border-green-500/30",
        bar: "bg-green-500",
        label: "UDISE Ready",
        emoji: "🟢",
      },
      good: {
        bg: "bg-blue-500/10",
        text: "text-blue-400",
        border: "border-blue-500/30",
        bar: "bg-blue-500",
        label: "Good",
        emoji: "🔵",
      },
      partial: {
        bg: "bg-yellow-500/10",
        text: "text-yellow-400",
        border: "border-yellow-500/30",
        bar: "bg-yellow-500",
        label: "Partial",
        emoji: "🟡",
      },
      pending: {
        bg: "bg-red-500/10",
        text: "text-red-400",
        border: "border-red-500/30",
        bar: "bg-red-500",
        label: "Pending",
        emoji: "🔴",
      },
    };
    return map[status];
  }